version: '3.9'

services:
  teamspeak:
    image: ${IMAGE_TEAMSPEAK_NAME}:${IMAGE_TEAMSPEAK_VERSION}
    restart: always
    ports:
    - 9987:9987/udp
    - 10011:10011
    - 30033:30033
    env_file:
    - .env.ts
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_DB_CONNECTIONS: 1
      TS3SERVER_LICENSE: accept
      TS3SERVER_LOG_APPEND: 1
#    extra_hosts:
#    - accounting.teamspeak.com:127.0.0.1
#    - backupaccounting.teamspeak.com:127.0.0.1
#    - ipcheck.teamspeak.com:127.0.0.1
    volumes:
    #START - only for linux
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    #END - only for linux
    - .docker/data/ts:/var/ts3server
    depends_on:
    - db
    healthcheck:
      test: nc -uz localhost 9987 && nc -z localhost 10011 && nc -z localhost 30033
      interval: 10s
      timeout: 3s
      retries: 25
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 100M
        reservations:
          cpus: '0.10'
          memory: 20M

  db:
    image: ${IMAGE_DB_NAME}:${IMAGE_DB_VERSION}
    restart: always
    secrets:
    - db_root_password
    - db_password
    env_file:
    - .env.db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
    #START - only for linux
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    #END - only for linux
    - .docker/data/db:/var/lib/mysql
    - .docker/db/conf.d/teamspeak.cnf:/etc/mysql/conf.d/teamspeak.cnf:ro
    healthcheck:
      test: mysqladmin ping -p$$(cat $${MYSQL_ROOT_PASSWORD_FILE})
      interval: 5s
      timeout: 2s
      retries: 25
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.20'
          memory: 100M

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
